### ISSUE TITLE
I have the same problem about vercel deployment, can you help me, thank you very much

### ISSUE THREAD

**Issue by zhl-2022** [WhiteHeadbanger/blog#1]
Error: No more than 12 Serverless Functions can be added to a Deployment on the Hobby plan. Create a team (Pro plan) to deploy more. Learn More: https://vercel.link/function-count-limit

![image](https://github.com/user-attachments/assets/385207f0-f5e0-44d1-97f9-25e9a0d70111)

![image](https://github.com/user-attachments/assets/ba30dfc3-6d44-4710-a245-fe9279153b66)

![image](https://github.com/user-attachments/assets/5fdae63d-f695-48b8-b408-6014bb99c45e)

**Comment by zhl-2022** [comment]
https://github.com/zhl-2022/myblog/blob/dev
 this is my blog site

**Comment by WhiteHeadbanger** [comment]
Hello, if I recall correctly what I did is reduce the number of functions that my code runs, and that fixed it

**Comment by zhl-2022** [comment]
I don't have more than 12 routing functions. Where do you mean 12 functions? If it's 12 functions for the entire project, I see your project has more than 12.thank you very much



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/03/2024 01:05 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [WhiteHeadbanger/blog] I have the same problem about vercel deployment, can you help me, thank you very much (Issue #1) |

Hello, if I recall correctly what I did is reduce the number of functions that my code runs, and that fixed it
